### ISSUE TITLE
how to compute sign and nonce byte

### ISSUE THREAD

**Issue by joshuaqb** [hydren-crypto/stampchain#161]
https://github.com/hydren-crypto/stampchain/blob/87daa8790bfdfcc17f9490209ca8779d884fb0d8/docs/src20.md?plain=1#L251

how to compute sign and nonce byte if we want to build transaction by ourselves?

Is there any code reference to build src20 transaction?

**Comment by reinamora137** [comment]
There is some code documentation now at:

https://github.com/stampchain-io/stamps_sdk/tree/main/core/utils
