### ISSUE TITLE
Missing Assets A1953185209141994500 & A1953185209141994501

### ISSUE THREAD

**Issue by moonblink** [hydren-crypto/stampchain#41]
These are missing from stampchain.io and appear to be valid stamps.

Raw Data from CP API for reference
```
{"result": [{"asset": "A1953185209141994500", "asset_longname": null, "owner": "1JDogZS6tQcSxwfxhv6XKKjcyicYA4Feev", "divisible": false, "locked": true, "supply": 100, "description": "STAMP:iVBORw0KGgoAAAANSUhEUgAAAB8AAAAfAQMAAAAlYIR6AAAACGFjVEwAAAAYAAAAANndHFMAAAAGUExURQAAAAjhGYh6ghoAAAABdFJOUwBA5thmAAAAGmZjVEwAAAAAAAAAHwAAAB8AAAAAAAAAAAAUAGQAAJ4YZK4AAAAWSURBVAjXY3jyzs+PYckqLy8IaxABAOZaBr9j9GxMAAAAGmZjVEwAAAABAAAAHgAAAAMAAAAAAAAABAAUAGQAACdRHJoAAAAYZmRBVAAAAAII12N45+fyhGGVl8sSMAsAMhEGpUzAF7wAAAAaZmNUTAAAAAMAAAAfAAAAAwAAAAAAAAAIABQAZAAA2oUlXwAAABhmZEFUAAAABAjXY3jy7sk7hiWrlqwCswBKIwnl1BHRngAAABpmY1RMAAAABQAAAB4AAAADAAAAAAAAAAwAFABkAAAU4vNuAAAAF2ZkQVQAAAAGCNdjeOLn4sKwxAtIgFgAJ2cE64zwQpoAAAAaZmNUTAAAAAcAAAAeAAAAAwAAAAAAAAAQABQAZAAAWQrWPQAAABhmZEFUAAAACAjXY3ji98SFYYnXEhcwCwAyxwaLoo9njgAAABpmY1RMAAAACQAAAB8AAAADAAAAAAAAABQAFABkAACX1EMqAAAAGGZkQVQAAAAKCNdjeOf37h3DKq9Vq8AsAD7DCHmxcXEPAAAAGmZjVEwAAAALAAAAHwAAAAMAAAAAAAAAGAAUAGQAAL3i+rcAAAAYZmRBVAAAAAwI12N48s7lHcOSVS6rwCwAPsMIRZFguAsAAAAaZmNUTAAAAA0AAAAeAAAAAwAAAAAAAAAcABQAZAEAap4dxwAAABdmZEFUAAAADgjXY3ji5+LCsMQLSIBYACdnBOsRK5QoAAAAGmZjVEwAAAAPAAAAHwAAABsAAAAAAAAAAAAUAGQAAGJk2kUAAAAaZmRBVAAAABAI12N44vLEj2GJyxIvCGuAAABD6AaLwqtduQAAABpmY1RMAAAAEQAAAB4AAAADAAAAAAAAAAQAFABkAAAmI5rWAAAAGGZkQVQAAAASCNdjeOL35AnDEq8lS8AsADyHCCu6kjD2AAAAGmZjVEwAAAATAAAAHgAAAAMAAAAAAAAACAAUAGQAAAwVI0sAAAAYZmRBVAAAABQI12N44vLOhWGJyyoXMAsAMq0Gi9LrUeUAAAAaZmNUTAAAABUAAAAfAAAAAwAAAAAAAAAMABQAZAAAwnL1egAAABhmZEFUAAAAFgjXY3jn9+4dwyqvVavALAA+wwh5zZ5uLgAAABpmY1RMAAAAFwAAAB4AAAADAAAAAAAAABAAFABkAABYeFBxAAAAGGZkQVQAAAAYCNdjePLE7wnDkiVeS8AsAD4NCCu9+lGkAAAAGmZjVEwAAAAZAAAAHgAAAAMAAAAAAAAAFAAUAGQAAEFERT4AAAAXZmRBVAAAABoI12N44ufiwrDEC0iAWAAnZwTrvwDUVAAAABpmY1RMAAAAGwAAAB4AAAADAAAAAAAAABgAFABkAABrcvyjAAAAGGZkQVQAAAAcCNdjeOLy5AnDEpclS8AsADu3CBFeTkSaAAAAGmZjVEwAAAAdAAAAHgAAAAMAAAAAAAAAHAAUAGQBAGvsm4sAAAAYZmRBVAAAAB4I12N45/fuCcMqr1VLwCwAPicIX2Pkc/QAAAAaZmNUTAAAAB8AAAAfAAAAGwAAAAAAAAAAABQAZAAAYxZcCQAAABpmZEFUAAAAIAjXY3jn9+4dwyqvVasgrAECADe3CHnOhyjJAAAAGmZjVEwAAAAhAAAAHgAAAAMAAAABAAAABAAUAGQAAOQ6z8IAAAAYZmRBVAAAACII12PomHtnDkPH1JApYBYANfsHQHavMzoAAAAaZmNUTAAAACMAAAAdAAAAAwAAAAEAAAAIABQAZAAAbVrw9gAAABhmZEFUAAAAJAjXY5h7ovMEw1SPTg8wCwA1YwcbyTL47QAAABpmY1RMAAAAJQAAAB4AAAADAAAAAQAAAAwAFABkAADXiSA2AAAAGGZkQVQAAAAmCNdjmDP35B2GKVM9Q8AsADf4B4NJY+PYAAAAGmZjVEwAAAAnAAAAHQAAAAMAAAABAAAAEAAUAGQAADk3g8wAAAAXZmRBVAAAACgI12PomNPRwdAxBUiAWAAxfwaVp5V73QAAABpmY1RMAAAAKQAAAB4AAAADAAAAAQAAABQAFABkAACDXRAqAAAAGGZkQVQAAAAqCNdjmNMx9w7DlI6pIWAWADXsB0BsyuYQAAAAGmZjVEwAAAArAAAAHQAAAAMAAAABAAAAGAAUAGQAAAo9Lx4AAAAXZmRBVAAAACwI12OYe6ejg2FqCJAAsQA1bgcMnrySSQAAABpmY1RMAAAALQAAAB8AAAADAAAAAAAAABwAFABkAACmgqBGAAAAFWZkQVQAAAAuCNdjeAcEDKuAAMwCAEvDChmcZiPHAAAAAElFTkSuQmCC", "issuer": "1JDogZS6tQcSxwfxhv6XKKjcyicYA4Feev"}], "id": 0, "jsonrpc": "2.0"}

```
```
A1953185209141994501


{"result": [{"asset": "A1953185209141994501", "asset_longname": null, "owner": "1JDogZS6tQcSxwfxhv6XKKjcyicYA4Feev", "divisible": false, "locked": true, "supply": 100, "description": "STAMP:iVBORw0KGgoAAAANSUhEUgAAAB8AAAAfAgMAAABiwP6qAAAACGFjVEwAAAAYAAAAANndHFMAAAAJUExURQAAAAAAAAjhGa5+0hUAAAABdFJOUwBA5thmAAAAGmZjVEwAAAAAAAAAHwAAAB8AAAAAAAAAAAAUAGQAAJ4YZK4AAAAfSURBVBjTY1iZuhKIUlcwzEydCUSpMxAioRAQMgIZADABV2ZXrf1zAAAAGmZjVEwAAAABAAAAHgAAAAMAAAAAAAAABAAUAGQAAVBWLAwAAAAdZmRBVAAAAAII12NYsUJhhQIQMXR0KHQoABFcBAB9ywjhCpa3OgAAABpmY1RMAAAAAwAAAB8AAAADAAAAAAAAAAgAFABkAAGtghXJAAAAG2ZkQVQAAAAECNdjWKGwYgUIM3QodHSAMFwEAJ4bC9E/KNbZAAAAGmZjVEwAAAAFAAAAHgAAAAMAAAAAAAAADAAUAGQAAWPlw/gAAAAcZmRBVAAAAAYI12NYoaAARAoKDB0KCh0gBlwEAFYjBfHA83EtAAAAGmZjVEwAAAAHAAAAHgAAAAMAAAAAAAAAEAAUAGQAAS4N5qsAAAAdZmRBVAAAAAgI12NYoaCwAogVGDoUFDqAWAEuAgBpOwdpYgCp2AAAABpmY1RMAAAACQAAAB8AAAADAAAAAAAAABQAFABkAAHg03O8AAAAG2ZkQVQAAAAKCNdjWLFCYQUIMHR0KHSAAFwEALEzDUmr7/v7AAAAGmZjVEwAAAALAAAAHwAAAAMAAAAAAAAAGAAUAGQAAcrlyiEAAAAdZmRBVAAAAAwI12NYobBihQIQM3QodHQoADFcBACLAwpZ1qIjlQAAABpmY1RMAAAADQAAAB4AAAADAAAAAAAAABwAFABkAgE2tH6SAAAAHGZkQVQAAAAOCNdjWKGgAEQKCgwdCgodIAZcBABWIwXx7PjimgAAABpmY1RMAAAADwAAAB8AAAAbAAAAAAAAAAAAFABkAABiZNpFAAAAImZkQVQAAAAQCNdjWJmamgrEKxhmAhlAPAMhEgoBIcOMAQBSAEtSX7Fu3gAAABpmY1RMAAAAEQAAAB4AAAADAAAAAAAAAAQAFABkAAFRJKpAAAAAIGZkQVQAAAASCNdjWKGgsGKFwgoFhg4FhY4OhQ4FuAgAeWMI4XtW4bwAAAAaZmNUTAAAABMAAAAeAAAAAwAAAAAAAAAIABQAZAABexIT3QAAABxmZEFUAAAAFAjXY1ihoKCwAkgwdAAZHUACLgIAZksHaZ0doFAAAAAaZmNUTAAAABUAAAAfAAAAAwAAAAAAAAAMABQAZAABtXXF7AAAABtmZEFUAAAAFgjXY1ixQmEFCDB0dCh0gABcBACxMw1Jb48mJwAAABpmY1RMAAAAFwAAAB4AAAADAAAAAAAAABAAFABkAAEvf2DnAAAAIGZkQVQAAAAYCNdjWKGwQkFhxQoFhg6FDgWFjg4FuAgAeWMI4U0545wAAAAaZmNUTAAAABkAAAAeAAAAAwAAAAAAAAAUABQAZAABNkN1qAAAABxmZEFUAAAAGgjXY1ihoABECgoMHQoKHSAGXAQAViMF8U9Sjw8AAAAaZmNUTAAAABsAAAAeAAAAAwAAAAAAAAAYABQAZAABHHXMNQAAABxmZEFUAAAAHAjXY1ihoKCwAggZOoCMDiCEiwAAZNMHaZPPK/wAAAAaZmNUTAAAAB0AAAAeAAAAAwAAAAAAAAAcABQAZAIBN8b43gAAAB1mZEFUAAAAHgjXY1ixQmEFECgwdHQodACBAlwEAKKDC9FbVc5nAAAAGmZjVEwAAAAfAAAAHwAAABsAAAAAAAAAAAAUAGQAAGMWXAkAAAAkZmRBVAAAACAI12NYuTJ1JRCsYJg5M3UmEMxAiIRCQMgwYwAA84pOQnanejQAAAAaZmNUTAAAACEAAAAeAAAAAwAAAAEAAAAEABQAZAABkz3/VAAAAB5mZEFUAAAAIgjXY2hoaFq0aEHTAhBDSUmhSQEuAgCdOQuZTPyUVAAAABpmY1RMAAAAIwAAAB0AAAADAAAAAQAAAAgAFABkAAEaXcBgAAAAH2ZkQVQAAAAkCNdjaFq0oKGhaUEDQ5OSApCh0AAXAQCd6QuzoMrf1AAAABpmY1RMAAAAJQAAAB4AAAADAAAAAQAAAAwAFABkAADXiSA2AAAAHWZkQVQAAAAmCNdjmLZ02jIgWsAwLXVaGhAlwEUAuOgNqSaJ4x0AAAAaZmNUTAAAACcAAAAdAAAAAwAAAAEAAAAQABQAZAABTjCzWgAAABpmZEFUAAAAKAjXY2hoaFrQAAQghgKIARcBAKC1C+c6JqKrAAAAGmZjVEwAAAApAAAAHgAAAAMAAAABAAAAFAAUAGQAAfRaILwAAAAfZmRBVAAAACoI12NoWtDQ0LRo0QKGJgUgQ0lJAS4CAJ05C5mGTqsRAAAAGmZjVEwAAAArAAAAHQAAAAMAAAABAAAAGAAUAGQAAAo9Lx4AAAAeZmRBVAAAACwI12OYtmzZ0qlTpzYwTEtLSwUx4CIAt/kNkz1lorcAAAAaZmNUTAAAAC0AAAAfAAAAAwAAAAAAAAAcABQAZAAB0YWQ0AAAABVmZEFUAAAALgjXY1gBBQwdUAAXAQDHOw7BIsHj8gAAAABJRU5ErkJggg", "issuer": "1JDogZS6tQcSxwfxhv6XKKjcyicYA4Feev"}], "id": 0, "jsonrpc": "2.0"
```

reference trx:
```
curl -X POST http://127.0.0.1:4000/api/ --user rpc:$PASSWORD -H 'Content-Type: application/json; charset=UTF-8' -H 'Accept: application/json, text/javascript' --data-binary '{ "jsonrpc": "2.0", "id": 0, "method": "get_asset_info", "params": { "asset": "PEPEPARTY" } }'

```

**Comment by moonblink** [comment]
```
A1953185209141994500
68d463c4d19f0fa8c58bcc4f1bf267650929fc678e8869280b316748ecb19afd
```

**Comment by moonblink** [comment]
compare CP (above) to xchain data. was not able to 

https://xchain.io/api/tx/68d463c4d19f0fa8c58bcc4f1bf267650929fc678e8869280b316748ecb19afd

{"asset":"A1953185209141994500","asset_longname":"","block_index":783260,"description":"STAMP:iVBORw0KGgoAAAANSUhEUgAAAB8AAAAfAQMAAAAlYIR6AAAACGFjVEwAAAAYAAAAANndHFMAAAAGUExURQAAAAjhGYh6ghoAAAABdFJOUwBA5thmAAAAGmZjVEwAAAAAAAAAHwAAAB8AAAAAAAAAAAAUAGQAAJ4YZK4AAAAWSURBVAjXY3jyzs+PYckqLy8IaxABAOZaBr9j9GxMAAAAGmZjVEwAAAABAAAAHgAAAAMAAAAAAAAABAAUAGQAACdRHJoAAAAYZmRBVAAAAAII12N45+fyhGGVl8sSMAsAMhEGpUzAF7wAAAAaZmNUTAAAAAMAAAAfAAAAAwAAAAAAAAAIABQAZAAA2oUlXwAAABhmZEFUAAAABAjXY3jy7sk7hiWrlqwCswBKIwnl1BHRngAAABpmY1RMAAAABQAAAB4AAAADAAAAAAAAAAwAFABkAAAU4vNuAAAAF2ZkQVQAAAAGCNdjeOLn4sKwxAtIgFgAJ2cE64zwQpoAAAAaZmNUTAAAAAcAAAAeAAAAAwAAAAAAAAAQABQAZAAAWQrWPQAAABhmZEFUAAAACAjXY3ji98SFYYnXEhcwCwAyxwaLoo9njgAAABpmY1RMAAAACQAAAB8AAAADAAAAAAAAABQAFABkAACX1EMqAAAAGGZkQVQAAAAKCNdjeOf37h3DKq9Vq8AsAD7DCHmxcXEPAAAAGmZjVEwAAAALAAAAHwAAAAMAAAAAAAAAGAAUAGQAAL3i+rcAAAAYZmRBVAAAAAwI12N48s7lHcOSVS6rwCwAPsMIRZFguAsAAAAaZmNUTAAAAA0AAAAeAAAAAwAAAAAAAAAcABQAZAEAap4dxwAAABdmZEFUAAAADgjXY3ji5+LCsMQLSIBYACdnBOsRK5QoAAAAGmZjVEwAAAAPAAAAHwAAABsAAAAAAAAAAAAUAGQAAGJk2kUAAAAaZmRBVAAAABAI12N44vLEj2GJyxIvCGuAAABD6AaLwqtduQAAABpmY1RMAAAAEQAAAB4AAAADAAAAAAAAAAQAFABkAAAmI5rWAAAAGGZkQVQAAAASCNdjeOL35AnDEq8lS8AsADyHCCu6kjD2AAAAGmZjVEwAAAATAAAAHgAAAAMAAAAAAAAACAAUAGQAAAwVI0sAAAAYZmRBVAAAABQI12N44vLOhWGJyyoXMAsAMq0Gi9LrUeUAAAAaZmNUTAAAABUAAAAfAAAAAwAAAAAAAAAMABQAZAAAwnL1egAAABhmZEFUAAAAFgjXY3jn9+4dwyqvVavALAA+wwh5zZ5uLgAAABpmY1RMAAAAFwAAAB4AAAADAAAAAAAAABAAFABkAABYeFBxAAAAGGZkQVQAAAAYCNdjePLE7wnDkiVeS8AsAD4NCCu9+lGkAAAAGmZjVEwAAAAZAAAAHgAAAAMAAAAAAAAAFAAUAGQAAEFERT4AAAAXZmRBVAAAABoI12N44ufiwrDEC0iAWAAnZwTrvwDUVAAAABpmY1RMAAAAGwAAAB4AAAADAAAAAAAAABgAFABkAABrcvyjAAAAGGZkQVQAAAAcCNdjeOLy5AnDEpclS8AsADu3CBFeTkSaAAAAGmZjVEwAAAAdAAAAHgAAAAMAAAAAAAAAHAAUAGQBAGvsm4sAAAAYZmRBVAAAAB4I12N45\/fuCcMqr1VLwCwAPicIX2Pkc\/QAAAAaZmNUTAAAAB8AAAAfAAAAGwAAAAAAAAAAABQAZAAAYxZcCQAAABpmZEFUAAAAIAjXY3jn9+4dwyqvVasgrAECADe3CHnOhyjJAAAAGmZjVEwAAAAhAAAAHgAAAAMAAAABAAAABAAUAGQAAOQ6z8IAAAAYZmRBVAAAACII12PomHtnDkPH1JApYBYANfsHQHavMzoAAAAaZmNUTAAAACMAAAAdAAAAAwAAAAEAAAAIABQAZAAAbVrw9gAAABhmZEFUAAAAJAjXY5h7ovMEw1SPTg8wCwA1YwcbyTL47QAAABpmY1RMAAAAJQAAAB4AAAADAAAAAQAAAAwAFABkAADXiSA2AAAAGGZkQVQAAAAmCNdjmDP35B2GKVM9Q8AsADf4B4NJY+PYAAAAGmZjVEwAAAAnAAAAHQAAAAMAAAABAAAAEAAUAGQAADk3g8wAAAAXZmRBVAAAACgI12PomNPRwdAxBUiAWAAxfwaVp5V73QAAABpmY1RMAAAAKQAAAB4AAAADAAAAAQAAABQAFABkAACDXRAqAAAAGGZkQVQAAAAqCNdjmNMx9w7DlI6pIWAWADXsB0BsyuYQAAAAGmZjVEwAAAArAAAAHQAAAAMAAAABAAAAGAAUAGQAAAo9Lx4AAAAXZmRBVAAAACwI12OYe6ejg2FqCJAAsQA1bgcMnrySSQAAABpmY1RMAAAALQAAAB8AAAADAAAAAAAAABwAFABkAACmgqBGAAAAFWZkQVQAAAAuCNdjeAcEDKuAAMwCAEvDChmcZiPHAAAAAElFTkSuQmCC","divisible":false,"fee":"0.00000000","issuer":"1JDogZS6tQcSxwfxhv6XKKjcyicYA4Feev","locked":true,"quantity":"100","reset":false,"source":"1JDogZS6tQcSxwfxhv6XKKjcyicYA4Feev","status":"valid","timestamp":1680225130,"transfer":false,"tx_hash":"68d463c4d19f0fa8c58bcc4f1bf267650929fc678e8869280b316748ecb19afd","tx_index":2275909,"tx_type":"Issuance"}

https://xchain.io/api/asset/A1953185209141994500

{"asset":"A1953185209141994500","asset_id":1953185209141994500,"asset_longname":"","description":"STAMP:iVBORw0KGgoAAAANSUhEUgAAAB8AAAAfAQMAAAAlYIR6AAAACGFjVEwAAAAYAAAAANndHFMAAAAGUExURQAAAAjhGYh6ghoAAAABdFJOUwBA5thmAAAAGmZjVEwAAAAAAAAAHwAAAB8AAAAAAAAAAAAUAGQAAJ4YZK4AAAAWSURBVAjXY3jyzs+PYckqLy8IaxABAOZaBr9j9GxMAAAAGmZjVEwAAAABAAAAHgAAAAMAAAAAAAAABAAUAGQAACdRHJoAAAAYZmRBVAAAAAII12N45+fyhGGVl8sSMAsAMhEGpUzAF7wAAAAaZmNUTAAAAAMAAAAfAAAAAwAAAAAAAAAIABQAZAAA2oUlXwAAABhmZEFUAAAABAjXY3jy7sk7hiWrlqwCswBKIwnl1BHRngAAABpmY1RMAAAABQAAAB4AAAADAAAAAAAAAAwAFABkAAAU4vNuAAAAF2ZkQVQAAAAGCNdjeOLn4sKwxAtIgFgAJ2cE64zwQpoAAAAaZmNUTAAAAAcAAAAeAAAAAwAAAAAAAAAQABQAZAAAWQrWPQAAABhmZEFUAAAACAjXY3ji98SFYYnXEhcwCwAyxwaLoo9njgAAABpmY1RMAAAACQAAAB8AAAADAAAAAAAAABQAFABkAACX1EMqAAAAGGZkQVQAAAAKCNdjeOf37h3DKq9Vq8AsAD7DCHmxcXEPAAAAGmZjVEwAAAALAAAAHwAAAAMAAAAAAAAAGAAUAGQAAL3i+rcAAAAYZmRBVAAAAAwI12N48s7lHcOSVS6rwCwAPsMIRZFguAsAAAAaZmNUTAAAAA0AAAAeAAAAAwAAAAAAAAAcABQAZAEAap4dxwAAABdmZEFUAAAADgjXY3ji5+LCsMQLSIBYACdnBOsRK5QoAAAAGmZjVEwAAAAPAAAAHwAAABsAAAAAAAAAAAAUAGQAAGJk2kUAAAAaZmRBVAAAABAI12N44vLEj2GJyxIvCGuAAABD6AaLwqtduQAAABpmY1RMAAAAEQAAAB4AAAADAAAAAAAAAAQAFABkAAAmI5rWAAAAGGZkQVQAAAASCNdjeOL35AnDEq8lS8AsADyHCCu6kjD2AAAAGmZjVEwAAAATAAAAHgAAAAMAAAAAAAAACAAUAGQAAAwVI0sAAAAYZmRBVAAAABQI12N44vLOhWGJyyoXMAsAMq0Gi9LrUeUAAAAaZmNUTAAAABUAAAAfAAAAAwAAAAAAAAAMABQAZAAAwnL1egAAABhmZEFUAAAAFgjXY3jn9+4dwyqvVavALAA+wwh5zZ5uLgAAABpmY1RMAAAAFwAAAB4AAAADAAAAAAAAABAAFABkAABYeFBxAAAAGGZkQVQAAAAYCNdjePLE7wnDkiVeS8AsAD4NCCu9+lGkAAAAGmZjVEwAAAAZAAAAHgAAAAMAAAAAAAAAFAAUAGQAAEFERT4AAAAXZmRBVAAAABoI12N44ufiwrDEC0iAWAAnZwTrvwDUVAAAABpmY1RMAAAAGwAAAB4AAAADAAAAAAAAABgAFABkAABrcvyjAAAAGGZkQVQAAAAcCNdjeOLy5AnDEpclS8AsADu3CBFeTkSaAAAAGmZjVEwAAAAdAAAAHgAAAAMAAAAAAAAAHAAUAGQBAGvsm4sAAAAYZmRBVAAAAB4I12N45\/fuCcMqr1VLwCwAPicIX2Pkc\/QAAAAaZmNUTAAAAB8AAAAfAAAAGwAAAAAAAAAAABQAZAAAYxZcCQAAABpmZEFUAAAAIAjXY3jn9+4dwyqvVasgrAECADe3CHnOhyjJAAAAGmZjVEwAAAAhAAAAHgAAAAMAAAABAAAABAAUAGQAAOQ6z8IAAAAYZmRBVAAAACII12PomHtnDkPH1JApYBYANfsHQHavMzoAAAAaZmNUTAAAACMAAAAdAAAAAwAAAAEAAAAIABQAZAAAbVrw9gAAABhmZEFUAAAAJAjXY5h7ovMEw1SPTg8wCwA1YwcbyTL47QAAABpmY1RMAAAAJQAAAB4AAAADAAAAAQAAAAwAFABkAADXiSA2AAAAGGZkQVQAAAAmCNdjmDP35B2GKVM9Q8AsADf4B4NJY+PYAAAAGmZjVEwAAAAnAAAAHQAAAAMAAAABAAAAEAAUAGQAADk3g8wAAAAXZmRBVAAAACgI12PomNPRwdAxBUiAWAAxfwaVp5V73QAAABpmY1RMAAAAKQAAAB4AAAADAAAAAQAAABQAFABkAACDXRAqAAAAGGZkQVQAAAAqCNdjmNMx9w7DlI6pIWAWADXsB0BsyuYQAAAAGmZjVEwAAAArAAAAHQAAAAMAAAABAAAAGAAUAGQAAAo9Lx4AAAAXZmRBVAAAACwI12OYe6ejg2FqCJAAsQA1bgcMnrySSQAAABpmY1RMAAAALQAAAB8AAAADAAAAAAAAABwAFABkAACmgqBGAAAAFWZkQVQAAAAuCNdjeAcEDKuAAMwCAEvDChmcZiPHAAAAAElFTkSuQmCC","divisible":false,"estimated_value":{"btc":"0.00000000","usd":"0.00000000","xcp":"0.00000000"},"issuer":"1JDogZS6tQcSxwfxhv6XKKjcyicYA4Feev","locked":true,"market_info":{"btc":{"floor":"0.00000000","price":"0.00000000"},"xcp":{"floor":"0.00000000","price":"0.00000000"}},"owner":"1JDogZS6tQcSxwfxhv6XKKjcyicYA4Feev","supply":100,"type":"numeric"}

**Comment by moonblink** [comment]
The 500 stamp is here: https://stampchain.io/stamps/68d463c4d19f0fa8c58bcc4f1bf267650929fc678e8869280b316748ecb19afd.png

**Comment by moonblink** [comment]
invalid base64 returned on 4501: 

{'asset': 'A1953185209141994501', 'asset_longname': None, 'block_index': 783260, 'call_date': 0, 'call_price': 0.0, 'callable': False, 'description': 'STAMP:iVBORw0KGgoAAAANSUhEUgAAAB8AAAAfAgMAAABiwP6qAAAACGFjVEwAAAAYAAAAANndHFMAAAAJUExURQAAAAAAAAjhGa5+0hUAAAABdFJOUwBA5thmAAAAGmZjVEwAAAAAAAAAHwAAAB8AAAAAAAAAAAAUAGQAAJ4YZK4AAAAfSURBVBjTY1iZuhKIUlcwzEydCUSpMxAioRAQMgIZADABV2ZXrf1zAAAAGmZjVEwAAAABAAAAHgAAAAMAAAAAAAAABAAUAGQAAVBWLAwAAAAdZmRBVAAAAAII12NYsUJhhQIQMXR0KHQoABFcBAB9ywjhCpa3OgAAABpmY1RMAAAAAwAAAB8AAAADAAAAAAAAAAgAFABkAAGtghXJAAAAG2ZkQVQAAAAECNdjWKGwYgUIM3QodHSAMFwEAJ4bC9E/KNbZAAAAGmZjVEwAAAAFAAAAHgAAAAMAAAAAAAAADAAUAGQAAWPlw/gAAAAcZmRBVAAAAAYI12NYoaAARAoKDB0KCh0gBlwEAFYjBfHA83EtAAAAGmZjVEwAAAAHAAAAHgAAAAMAAAAAAAAAEAAUAGQAAS4N5qsAAAAdZmRBVAAAAAgI12NYoaCwAogVGDoUFDqAWAEuAgBpOwdpYgCp2AAAABpmY1RMAAAACQAAAB8AAAADAAAAAAAAABQAFABkAAHg03O8AAAAG2ZkQVQAAAAKCNdjWLFCYQUIMHR0KHSAAFwEALEzDUmr7/v7AAAAGmZjVEwAAAALAAAAHwAAAAMAAAAAAAAAGAAUAGQAAcrlyiEAAAAdZmRBVAAAAAwI12NYobBihQIQM3QodHQoADFcBACLAwpZ1qIjlQAAABpmY1RMAAAADQAAAB4AAAADAAAAAAAAABwAFABkAgE2tH6SAAAAHGZkQVQAAAAOCNdjWKGgAEQKCgwdCgodIAZcBABWIwXx7PjimgAAABpmY1RMAAAADwAAAB8AAAAbAAAAAAAAAAAAFABkAABiZNpFAAAAImZkQVQAAAAQCNdjWJmamgrEKxhmAhlAPAMhEgoBIcOMAQBSAEtSX7Fu3gAAABpmY1RMAAAAEQAAAB4AAAADAAAAAAAAAAQAFABkAAFRJKpAAAAAIGZkQVQAAAASCNdjWKGgsGKFwgoFhg4FhY4OhQ4FuAgAeWMI4XtW4bwAAAAaZmNUTAAAABMAAAAeAAAAAwAAAAAAAAAIABQAZAABexIT3QAAABxmZEFUAAAAFAjXY1ihoKCwAkgwdAAZHUACLgIAZksHaZ0doFAAAAAaZmNUTAAAABUAAAAfAAAAAwAAAAAAAAAMABQAZAABtXXF7AAAABtmZEFUAAAAFgjXY1ixQmEFCDB0dCh0gABcBACxMw1Jb48mJwAAABpmY1RMAAAAFwAAAB4AAAADAAAAAAAAABAAFABkAAEvf2DnAAAAIGZkQVQAAAAYCNdjWKGwQkFhxQoFhg6FDgWFjg4FuAgAeWMI4U0545wAAAAaZmNUTAAAABkAAAAeAAAAAwAAAAAAAAAUABQAZAABNkN1qAAAABxmZEFUAAAAGgjXY1ihoABECgoMHQoKHSAGXAQAViMF8U9Sjw8AAAAaZmNUTAAAABsAAAAeAAAAAwAAAAAAAAAYABQAZAABHHXMNQAAABxmZEFUAAAAHAjXY1ihoKCwAggZOoCMDiCEiwAAZNMHaZPPK/wAAAAaZmNUTAAAAB0AAAAeAAAAAwAAAAAAAAAcABQAZAIBN8b43gAAAB1mZEFUAAAAHgjXY1ixQmEFECgwdHQodACBAlwEAKKDC9FbVc5nAAAAGmZjVEwAAAAfAAAAHwAAABsAAAAAAAAAAAAUAGQAAGMWXAkAAAAkZmRBVAAAACAI12NYuTJ1JRCsYJg5M3UmEMxAiIRCQMgwYwAA84pOQnanejQAAAAaZmNUTAAAACEAAAAeAAAAAwAAAAEAAAAEABQAZAABkz3/VAAAAB5mZEFUAAAAIgjXY2hoaFq0aEHTAhBDSUmhSQEuAgCdOQuZTPyUVAAAABpmY1RMAAAAIwAAAB0AAAADAAAAAQAAAAgAFABkAAEaXcBgAAAAH2ZkQVQAAAAkCNdjaFq0oKGhaUEDQ5OSApCh0AAXAQCd6QuzoMrf1AAAABpmY1RMAAAAJQAAAB4AAAADAAAAAQAAAAwAFABkAADXiSA2AAAAHWZkQVQAAAAmCNdjmLZ02jIgWsAwLXVaGhAlwEUAuOgNqSaJ4x0AAAAaZmNUTAAAACcAAAAdAAAAAwAAAAEAAAAQABQAZAABTjCzWgAAABpmZEFUAAAAKAjXY2hoaFrQAAQghgKIARcBAKC1C+c6JqKrAAAAGmZjVEwAAAApAAAAHgAAAAMAAAABAAAAFAAUAGQAAfRaILwAAAAfZmRBVAAAACoI12NoWtDQ0LRo0QKGJgUgQ0lJAS4CAJ05C5mGTqsRAAAAGmZjVEwAAAArAAAAHQAAAAMAAAABAAAAGAAUAGQAAAo9Lx4AAAAeZmRBVAAAACwI12OYtmzZ0qlTpzYwTEtLSwUx4CIAt/kNkz1lorcAAAAaZmNUTAAAAC0AAAAfAAAAAwAAAAAAAAAcABQAZAAB0YWQ0AAAABVmZEFUAAAALgjXY1gBBQwdUAAXAQDHOw7BIsHj8gAAAABJRU5ErkJggg', 'divisible': False, 'fee_paid': 0, 'issuer': '1JDogZS6tQcSxwfxhv6XKKjcyicYA4Feev', 'locked': True, 'quantity': 100, 'reset': False, 'source': '1JDogZS6tQcSxwfxhv6XKKjcyicYA4Feev', 'status': 'valid', 'transfer': False, 'tx_hash': 'f46a59c3c49b14e2bae3a64ff1a5e5c05ae8dbaf547237afe305f2f359e6f807', 'tx_index': 2275910} ***base64 False***

**Comment by moonblink** [comment]
A1953185209141994501 - Invalid base64 image string: Incorrect padding

**Comment by hydren-crypto** [comment]
the base64 or 501 was not properly encoding:

When decoding a base64 string in Python, you may encounter an "Incorrect padding" error if the input string is not properly padded. Base64 encoding requires that the input be padded with '=' characters to make its length a multiple of 4. You can fix the padding issue by adding the required number of '=' characters to the end of the input string before decoding it.

Now we are fixing up the padding, and stripping whitespaces from the string to include "stamp: BaSe64xxx" formats. This caused a renumbering but was prudent to include these minor decoding peculiarities.
