### ISSUE TITLE
missing assets

### ISSUE THREAD

**Issue by hydren-crypto** [hydren-crypto/stampchain#48]
stamps didn't stamp but i have the transaction data in my wallet https://xchain.io/asset/A1594743328999796200
https://xchain.io/asset/A13909955724034337000 do you know what has gone wrong? how do i get my stamps? thank you!!!

@JoBloggss

**Comment by hydren-crypto** [comment]
named asset snuck through the filter as well.  https://stampchain.io/asset.html?stampNumber=400  Asset EGGSTAMPS

**Comment by moonblink** [comment]
A1594743328999796200 d0a29e742187903c2f99742f03be078cc650bd3222a628ad6f5dde64d02c523a.svg
https://stampchain.io/stamps/d0a29e742187903c2f99742f03be078cc650bd3222a628ad6f5dde64d02c523a.svg

A13909955724034337000 bbedc3c00f131681e0fdc12b5f7ab04c4eeea6096a66a14c89e3eebd44dd4bfc.png
https://stampchain.io/stamps/bbedc3c00f131681e0fdc12b5f7ab04c4eeea6096a66a14c89e3eebd44dd4bfc.png

this looks like a rendering issue on the base64 decoding, but they are in the stamp directory.

**Comment by hydren-crypto** [comment]
rejected stamps have been added here:

https://stampchain.io/invalid_stamp.json
